### ISSUE TITLE
Fimware.bin flash bootloop

### ISSUE THREAD

**Issue by lyazide** [OzInFl/CLIPPER1#3]
Very nice project, at least from what I see as for the moment I can not upload the firmware to the ESP32-S3.
When I upload it with ESP Flash Download it goes in boot loop. I flash using the address 0 for the start of the firmware.bin.*

I am noop on such boards, then any help is welcome.

**Comment by lyazide** [comment]
Ok I solved it by compiling and uploading it from Visual studio Code.

**Comment by OzInFl** [comment]
Glad to hear you got it solved!
